# Generated by Django 5.0.14 on 2026-06-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('manifesto', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['gender', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
                'ordering': ['standard', 'division'],
                'unique_together': {('standard', 'division')},
            },
        ),
        migrations.CreateModel(
            name='ElectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_enabled', models.BooleanField(default=True)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.schoolclass')),
            ],
            options={
                'verbose_name': 'Election Setting',
                'verbose_name_plural': 'Election Settings',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField()),
                ('division', models.CharField(max_length=1)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('female_candidate', models.ForeignKey(limit_choices_to={'gender': 'Female'}, on_delete=django.db.models.deletion.PROTECT, related_name='female_votes', to='election.candidate')),
                ('male_candidate', models.ForeignKey(limit_choices_to={'gender': 'Male'}, on_delete=django.db.models.deletion.PROTECT, related_name='male_votes', to='election.candidate')),
            ],
        ),
    ]
